### ISSUE TITLE
Regtest doesn't work as env

### ISSUE THREAD

**Issue by patricklodder** [dogecoin/docker#28]
When using `-e REGTEST=1`, the daemon starts for mainnet:

```
$ docker run -e REGTEST=1 e4d68febe0e9 |grep Bound
2021-12-04 18:45:56 Bound to [::]:22556
2021-12-04 18:45:56 Bound to 0.0.0.0:22556
```

but when using -regtest, the daemon starts for regtest:

```
$ docker run e4d68febe0e9 -regtest |grep Bound
2021-12-04 18:48:17 Bound to [::]:18444
2021-12-04 18:48:17 Bound to 0.0.0.0:18444
```

Probably related to our discussion at https://github.com/dogecoin/docker/pull/3#issuecomment-967529051 ?

**Comment by AbcSxyZ** [comment]
> Probably related to our discussion at #3 (comment) ?

Yes, it is, the option is not appearing in the man. I understand more the problem, I didn't realize `-help-debug` is adding extra flags in the help menu.

As a possible solution, I think it would be to use the output of `--help` commands instead of man pages to get existing options, and adding `help-debug` flag when doing it for `dogecoind`/`dogecoin-qt` to get all options.

Adding some hard coded values :speak_no_evil: for those debug options :-1:. I don't think it's a solution, but it can solve the problem.

Or let the user specify those options by arguments, we may not provide support for those environment variables (for now, until someone really push for it because it's important for this person).

**Comment by patricklodder** [comment]
> As a possible solution, I think it would be to use the output of --help commands instead of man pages to get existing options, and adding help-debug flag when doing it for dogecoind/dogecoin-qt to get all options.

Agree re: dogecoind. I think we need to have a separate discussion about exposing Dogecoin QT in containers.

> Or let the user specify those options by arguments, we may not provide support for those environment variables (for now, until someone really push for it because it's important for this person).

Hmm... I like the idea of ENV over args, especially if I consider how I normally use things like k8s secrets in production environments, which is a must-have for passwords, eg the RPC password. So I'd vote "take `dogecoind -help -help-debug` output" over "let's give up on env".
